<a href="https://colab.research.google.com/github/brzenio/R_study/blob/main/R4_2711.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Książki do R:

https://ksiegarnia.pwn.pl/Programowanie-w-jezyku-R,647767533,p.html

Na przełaj przez Data Mining z pakietem R

http://www.biecek.pl/R/

https://github.com/mim-uw/eXplainableMachineLearning-2023

https://github.com/mim-uw/MachineLearningSeminar



Zadanie 1: Napisz program tworzacy pusta macierz.

In [ ]:
mat = matrix(, nrow = 1, ncol = 1)
mat

[,1]
[1,] NA

Zadanie 2: Napisz program tworzacy macierz przyjmujac jako dane wejsciowe podany wektor liczb. Wyswietl macierz.

In [6]:
m_vec = matrix(c(1, 2, 3, 4), 2, 2)
m_vec

[,1] [,2]
[1,] 1    3   
[2,] 2    4

Zadanie 3: Napisz program, ktory utworzy macierz przyjmujac jako dane wejsciowe podany wektor liczb i zdefiniuje nazwy kolumn i wierszy. Wyświetl macierz.

In [8]:
colnames(m_vec) <- c("Kolumna 1", "Kolumna 2")
rownames(m_vec) <- c("Wiersz 1", "Wiersz 2")
m_vec

Kolumna 1 Kolumna 2
Wiersz 1 1         3        
Wiersz 2 2         4

Zadanie 4: Napisz program uzyskujacy dostep do elementu w 3 kolumnie i 2 wierszu; tylko 3 wierszu i tylko 4 kolumnie danej macierzy.

In [14]:
m <- matrix(1:12, nrow = 3, ncol = 4)
colnames(m) <- c("col1", "col2", "col3", "col4")
rownames(m) <- c("row1", "row2", "row3")

# Dostęp do elementu w 3 kolumnie i 2 wierszu
m[2,3]

# Dostęp tylko do 3 wierszy i 4 kolumn
m[3,4]

[1] 8

[1] 12

Zadanie 5: Napisz program tworzacy dwie macierze 2x3. Dodawaj, odejmij, pomnoz i podziel macierze.

In [17]:
mat1 <- matrix(1:6, nrow = 2, ncol = 3)

mat2 <- matrix(7:12, nrow = 2, ncol = 3)

mat1
mat2

# Dodawanie macierzy
mat_sum <- mat1 + mat2

# Odejmowanie macierzy
mat_diff <- mat1 - mat2

# Mnozenie macierzy
mat_prod <- mat1 * mat2

# Dzielenie macierzy
mat_quot <- mat1 / mat2

# Wyswietlanie wyniku
mat_sum
mat_diff
mat_prod
mat_quot

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 7     9   11  
[2,] 8    10   12

[,1] [,2] [,3]
[1,]  8   12   16  
[2,] 10   14   18

[,1] [,2] [,3]
[1,] -6   -6   -6  
[2,] -6   -6   -6

[,1] [,2] [,3]
[1,]  7   27   55  
[2,] 16   40   72

[,1]      [,2]      [,3]     
[1,] 0.1428571 0.3333333 0.4545455
[2,] 0.2500000 0.4000000 0.5000000

Zadanie 6: Napisz program tworzacy macierz z listy podanych wektorow.

In [19]:
vectors <- list(c(1, 2, 3), c(4, 5, 6), c(7, 8, 9))
matrix_from_vectors <- matrix(unlist(vectors), ncol = 3, byrow = TRUE)

matrix_from_vectors

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

Zadanie 7: Napisz program, ktory wyodrebni podmacierz, ktorej wiersze maja wartosc kolumny > 7 z danej macierzy.

In [35]:
# Do poprawy, bo nie działa
m <- matrix(1:12, 4, 3)
print (m)

submatrix <- m[m[, 1] > 7, ]

print(submatrix)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12
     [,1] [,2] [,3]


Zadanie 8: Napisz program konwertujacy dana macierz do listy wektorow kolumnowych.

In [36]:
m <- matrix(1:12, 4, 3)
column_vectors <- as.list(apply(m, 2, as.vector))

column_vectors

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] 6

[[7]]
[1] 7

[[8]]
[1] 8

[[9]]
[1] 9

[[10]]
[1] 10

[[11]]
[1] 11

[[12]]
[1] 12

Zadanie 9: Napisz program, ktory znajdzie indeks wierszy i kolumn o wartości maksymalnej i minimalnej w danej macierzy.

In [39]:
m <- matrix(1:12, 4, 3)
min_index <- which(m == min(m), arr.ind = TRUE)
max_index <- which(m == max(m), arr.ind = TRUE)

min_index
max_index

row col
[1,] 1   1

row col
[1,] 4   3

Zadanie 10: Napisz program, ktory obraca dana macierz o 90 stopni zgodnie z ruchem wskazowek zegara.

In [42]:
m <- matrix(1:12, 4, 3)
rotated_matrix <- t(apply(m, 2, rev))

m
rotated_matrix

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

[,1] [,2] [,3] [,4]
[1,]  4    3    2   1   
[2,]  8    7    6   5   
[3,] 12   11   10   9

Zadanie 11: Napisz program konwertujacy dana macierz na tablice jednowymiarowa.

In [45]:
m <- matrix(1:12, 4, 3)
arr <- as.vector(m)

arr

[1]  1  2  3  4  5  6  7  8  9 10 11 12

Zadanie 12: Napisz program tworzacy trojwymiarowa tablice 24 elementow za pomoca funkcji dim().

In [55]:
dim_tab <- array(1:24, dim = c(2, 3, 4))

# bez printu daje tylko ciąg znaków
print(dim_tab)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24



Zadanie 13: Napisz program tworzacy dwuwymiarowa tablice 5x3 sekwencji parzystych liczb calkowitych wiekszych niz 50.

In [58]:
even_num <- seq(52, by = 2, length.out = 15)
two_dim <- matrix(even_num, 5, 3)

two_dim

[,1] [,2] [,3]
[1,] 52   62   72  
[2,] 54   64   74  
[3,] 56   66   76  
[4,] 58   68   78  
[5,] 60   70   80

Zadanie 14:

a) Stworz macierz o rozmiarze "30x12".

b) Poczatkowa wartosc generatora liczb pseudolosowych powinna zostac ustalona na 222.

c) Pierwsza kolumna powinna zawierac 30 unikalnych wartosci losowych z wektora "1:30".

d) Ostatnia kolumna powinna zawierac 30 nieunikalnych wartosci losowych z wektora "1:3".

e) Pozostale kolumny powinny zawierac wartosci losowe pochodzace z rozkladu rownomiernego "runif()".

In [62]:
set.seed(222)
matrix_a <- matrix(nrow = 30, ncol = 12)

# Wypełnienie pierwszej kolumny unikalnymi wartościami z wektora 1:30
matrix_a[, 1] <- sample(1:30, 30, replace = FALSE)

# Wypełnienie ostatniej kolumny nieunikalnymi wartościami z wektora 1:3
matrix_a[, 12] <- sample(1:3, 30, replace = TRUE)

# Wypełnienie pozostałych kolumn wartościami losowymi z rozkładu rownomiernego
for (i in 2:(ncol(matrix_a)-1)) {
  matrix_a[, i] <- runif(30)
}

matrix_a

[,1] [,2]        [,3]      [,4]        [,5]       [,6]       [,7]      
 [1,] 29   0.007386262 0.5200866 0.466012557 0.11764201 0.01204664 0.34430962
 [2,] 15   0.827934417 0.4197993 0.002764619 0.07253714 0.52098024 0.39318973
 [3,] 18   0.508350033 0.7894482 0.066187902 0.84222002 0.82595176 0.07396162
 [4,] 23   0.580192872 0.8552275 0.522523874 0.44996045 0.41329303 0.65990270
 [5,] 24   0.761216660 0.6014042 0.274776342 0.41647060 0.84044814 0.72999920
 [6,] 22   0.689735584 0.6486873 0.475531986 0.70685066 0.63421046 0.13358783
 [7,] 20   0.569643423 0.8951410 0.516183041 0.59637592 0.39861887 0.75755543
 [8,]  9   0.284557480 0.8924557 0.118609249 0.76449309 0.70857120 0.26442632
 [9,] 10   0.845238734 0.1724698 0.955461593 0.67221471 0.14811799 0.93623392
[10,] 27   0.868492735 0.6242937 0.005716680 0.05806926 0.60143831 0.63660994
[11,] 28   0.862767064 0.6835176 0.963441837 0.66468886 0.49874447 0.22656102
[12,]  1   0.986415393 0.1483866 0.792056287 0.86373868 0.65047215 0.32177458
[13,] 14   0.455446823 0.5734342 0.572336961 0.37812071 0.05625480 0.07166112
[14,]  7   0.624447462 0.1254356 0.603489239 0.36976969 0.33432253 0.99683724
[15,] 21   0.860962112 0.3921239 0.575777713 0.27246998 0.60457539 0.52430580
[16,] 12   0.174817597 0.8908656 0.475080052 0.73118252 0.78839182 0.50980380
[17,] 13   0.350584868 0.5710436 0.153008437 0.02354180 0.59142367 0.15756866
[18,] 25   0.792080680 0.7850070 0.749123883 0.69455333 0.35697656 0.62473777
[19,]  5   0.402059959 0.3991554 0.862364277 0.72468212 0.06981060 0.70623899
[20,] 16   0.353694417 0.7730247 0.510840248 0.95415550 0.99962093 0.47320799
[21,] 19   0.774520554 0.6213252 0.396335447 0.21563253 0.36487561 0.74992428
[22,] 30   0.630470521 0.5229172 0.703883436 0.64785919 0.35988858 0.23636324
[23,]  6   0.427033795 0.8850669 0.503464754 0.79474517 0.70150033 0.58008925
[24,] 26   0.723882672 0.8003719 0.754760859 0.59307847 0.46600366 0.36345565
[25,]  3   0.086897224 0.7869521 0.850064185 0.87023766 0.74659112 0.94710433
[26,] 17   0.698770502 0.5792046 0.115238809 0.66457737 0.26060012 0.59694372
[27,]  4   0.526063273 0.7144496 0.774336503 0.33977732 0.22012720 0.03455435
[28,] 11   0.170537435 0.9266339 0.107644005 0.11802133 0.16966878 0.72653283
[29,]  2   0.083912129 0.1813995 0.003391463 0.04456505 0.51491163 0.36062352
[30,]  8   0.109782589 0.3227007 0.584409045 0.25991415 0.15917449 0.35298221
      [,8]       [,9]       [,10]       [,11]      [,12]
 [1,] 0.19938141 0.05642366 0.169486679 0.66863372 1    
 [2,] 0.35553358 0.65075027 0.614641651 0.19584498 2    
 [3,] 0.82311571 0.95426854 0.178001672 0.71325784 2    
 [4,] 0.01147872 0.95220542 0.810782351 0.40871553 3    
 [5,] 0.42245355 0.28136551 0.790953138 0.14646424 2    
 [6,] 0.45514697 0.95188715 0.350933912 0.30704497 1    
 [7,] 0.60282333 0.38923318 0.720670067 0.17967689 3    
 [8,] 0.73008884 0.79121032 0.703591940 0.32819625 1    
 [9,] 0.13798617 0.84702703 0.601097035 0.86780449 3    
[10,] 0.53082166 0.03723371 0.276599883 0.53656755 3    
[11,] 0.24516891 0.40745784 0.226195880 0.04500740 1    
[12,] 0.71612803 0.74459224 0.822514484 0.18298461 2    
[13,] 0.53609815 0.76235437 0.124217526 0.16713496 3    
[14,] 0.54646098 0.19895982 0.998309704 0.69003935 2    
[15,] 0.36934522 0.59556458 0.384662044 0.59666063 2    
[16,] 0.16932084 0.30607939 0.119606072 0.84408420 3    
[17,] 0.53797077 0.43728909 0.004445296 0.65294481 3    
[18,] 0.02871101 0.02851020 0.132673358 0.87778469 2    
[19,] 0.43468814 0.77804949 0.248589275 0.10393390 2    
[20,] 0.06814882 0.91987497 0.235018448 0.08889945 3    
[21,] 0.66568606 0.94932258 0.671616249 0.93887313 2    
[22,] 0.71200675 0.65934871 0.438218101 0.87203173 2    
[23,] 0.38895289 0.31856816 0.503319245 0.87952665 2    
[24,] 0.91159086 0.37388845 0.824515120 0.78933620 1    
[25,] 0.03291829 0.52993601 0.456119393 0.44642673 2    
[26,] 0.78368939 0.01424721 0.116968193 0.70729039 3    
[27,] 0.11852882 0.23969809 0.447843172 0.5618334