<a href="https://colab.research.google.com/github/brzenio/R_study/blob/main/R5_1112.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

adresy <- c("Kasztanowa 14, Bielsko Biała", "Łąki Zielonej 152, Katowice", "Specerowa 8, Elbląg")

produkty <- c("TV ", "laptop", " przenośna ładowarka", "Bezprzewodowa klawiatura", " SłuchaWki " )

dluga_sentencja <- stringr::sentences[1:10]

nazwa_pola <- c( "order_number", "order_date", "customer_email", "product_ title", "amount" )

pracownik_umiejetnosci <- c("Jan Kowalski (Beginner)", "Marta Górska (Pro)", "Krzysztof Biały (Pro)", "Sarah Machoń (Medium)")

In [ ]:
adresy <- c("Kasztanowa 14, Bielsko Biała", "Łąki Zielonej 152, Katowice", "Specerowa 8, Elbląg")
produkty <- c("TV ", "laptop", " przenośna ładowarka", "Bezprzewodowa klawiatura", " SłuchaWki " )
dluga_sentencja <- stringr::sentences[1:10]
nazwa_pola <- c( "order_number", "order_date", "customer_email", "product_ title", "amount" )
pracownik_umiejetnosci <- c("Jan Kowalski (Beginner)", "Marta Górska (Pro)", "Krzysztof Biały (Pro)", "Sarah Machoń (Medium)")

Zadanie 1: Normalizuj wektor adresów, zastępując wielkie litery małymi literami.

In [ ]:
adresy
adresy <- tolower(adresy)
adresy

[1] "Kasztanowa 14, Bielsko Biała" "Łąki Zielonej 152, Katowice" 
[3] "Specerowa 8, Elbląg"

[1] "kasztanowa 14, bielsko biała" "łąki zielonej 152, katowice" 
[3] "specerowa 8, elbląg"

Zadanie 2: Wybierz tylko liczbową część wektora adresów.

In [ ]:
adresy_liczbowe <- gsub("[^0-9]", "", adresy)
adresy_liczbowe

[1] "14"  "152" "8"

Zadanie 3: Podziel wektor adresów na dwie części: adres i miasto. Wynik powinien być macierzą.

In [ ]:
adresy_miasta <- strsplit(adresy, ",")
adresy_miasta <- lapply(adresy_miasta, function(x) c(x[1], x[2]))
adresy_miasta
adresy_miasta <- do.call(rbind, adresy_miasta)

adresy_miasta

[[1]]
[1] "Kasztanowa 14"  " Bielsko Biała"

[[2]]
[1] "Łąki Zielonej 152" " Katowice"        

[[3]]
[1] "Specerowa 8" " Elbląg"

[,1]              [,2]          
[1,] Kasztanowa 14      Bielsko Biała
[2,] Łąki Zielonej 152  Katowice     
[3,] Specerowa 8        Elbląg

Zadanie 4: Podziel wektor adresów na trzy części: numer domu, ulicę i miasto. Wynik powinien być macierzą. Podpowiedź: użyj asercji z wyrażeniem w tył regex.

In [ ]:
adresy <- c("ul. Wiejska 12", "ul. Krakowska 15", "ul. Kościuszki 20")

adresy_podzielone <- strsplit(adresy, " ")

adresy_macierz <- as.data.frame(adresy_podzielone)

colnames(adresy_macierz) <- c("Ulica", "Numer")
adresy_macierz

Ulica   Numer     <NA>      
1 ul.     ul.       ul.       
2 Wiejska Krakowska Kościuszki
3 12      15        20

In [ ]:
# Nie działa podział adresu na ulicę i numer, zapewne trzeba poprawić drugi warunek w strsplit

adresy_podzielone <- strsplit(adresy, " |, ", )
adresy_podzielone <- lapply(adresy_podzielone, function(x) c(x[2], x[1], x[3]))
adresy_podzielone <- do.call(rbind, adresy_podzielone)

adresy_podzielone


[,1]     [,2]       [,3]   
[1,] 14       Kasztanowa Bielsko
[2,] Zielonej Łąki       152    
[3,] 8        Specerowa  Elbląg

Zadanie 5:

W wektorze dluga_sentencja dla zdań zaczynających się na literę „T” lub kończących się na literę „s” pokaż odpowiednio pierwsze lub ostatnie słowo.

Jeśli zdanie zarówno zaczyna się na „T”, jak i kończy na „s”, pokaż zarówno pierwsze, jak i ostatnie słowo.

Pamiętaj, że faktyczny ostatni znak zdania to zwykle kropka.

In [ ]:
dluga_sentencja_zmieniona <- sapply(dluga_sentencja, function(x) {
  first_word <- strsplit(x, " ")[[1]][1]
  last_word <- strsplit(x, " ")[[1]][length(strsplit(x, " ")[[1]])]
  if (substr(x, 1, 1) == "T" & substr(last_word, nchar(last_word), nchar(last_word)) == "s") {
    paste(first_word, last_word)
  } else if (substr(x, 1, 1) == "T") {
    first_word
  } else if (substr(last_word, nchar(last_word), nchar(last_word)) == "s") {
    last_word
  } else {
    x
  }
})

dluga_sentencja_zmieniona

The birch canoe slid on the smooth planks. 
                                        "The" 
  Glue the sheet to the dark blue background. 
"Glue the sheet to the dark blue background." 
       It's easy to tell the depth of a well. 
     "It's easy to tell the depth of a well." 
     These days a chicken leg is a rare dish. 
                                      "These" 
         Rice is often served in round bowls. 
       "Rice is often served in round bowls." 
        The juice of lemons makes fine punch. 
                                        "The" 
  The box was thrown beside the parked truck. 
                                        "The" 
  The hogs were fed chopped corn and garbage. 
                                        "The" 
          Four hours of steady work faced us. 
        "Four hours of steady work faced us." 
     Large size in stockings is hard to sell. 
   "Large size in stockings is hard to sell."

Zadanie 6: Pokaż tylko pierwszych 20 znaków wszystkich zdań w wektorze dluga_sentencja Aby wskazać, że usunąłeś niektóre znaki, użyj dwóch kolejnych kropek na końcu każdego zdania.

In [ ]:
dluga_sentencja_skrocone <- substr(dluga_sentencja, 1, 20)
dluga_sentencja_skrocone <- paste0(dluga_sentencja_skrocone, "..")

dluga_sentencja_skrocone

[1] "The birch canoe slid.." "Glue the sheet to th.." "It's easy to tell th.."
 [4] "These days a chicken.." "Rice is often served.." "The juice of lemons .."
 [7] "The box was thrown b.." "The hogs were fed ch.." "Four hours of steady.."
[10] "Large size in stocki.."

Zadanie 7: Znormalizuj wektor produkty, usuwając wszystkie niepotrzebne spacje (zarówno na początku, na końcu, jak i w środku) oraz używając wielkich liter.

In [ ]:
produkty <- gsub(" ", "", produkty)
produkty <- toupper(produkty)

# wersja rozszerzona ???
# produkty <- gsub("^\\s+|\\s+$", "", produkty)
# produkty <- gsub("\\s+", " ", produkty)


produkty

[1] "TV"                      "LAPTOP"                 
[3] "PRZENOŚNAŁADOWARKA"      "BEZPRZEWODOWAKLAWIATURA"
[5] "SŁUCHAWKI"

Zadanie 8: Przygotuj wektor nazwa_pola, zastępując wszystkie symbole podkreśleń spacjami i konwertując je na wielkie litery.

In [ ]:
nazwa_pola
nazwa_pola <- gsub("_", " ", nazwa_pola)
nazwa_pola <- toupper(nazwa_pola)

nazwa_pola

[1] "order_number"   "order_date"     "customer_email" "product_ title"
[5] "amount"

[1] "ORDER NUMBER"   "ORDER DATE"     "CUSTOMER EMAIL" "PRODUCT  TITLE"
[5] "AMOUNT"

Zadanie 9: Wyrównaj wszystkie nazwa_pola, aby miały równą długość, dodając spacje na początku odpowiednich ciągów.

In [ ]:
max_length <- max(nchar(nazwa_pola))
max_length

# Trzeba coś poprawić w tej funkcji, gdzieś w warunku paste0 lub rep
nazwa_pola_rownej_dlugosci <- sapply(nazwa_pola, function(x) paste0(rep("-", max_length - nchar(x)), x))

print(nazwa_pola)
print(nazwa_pola_rownej_dlugosci)

[1] 14

[1] "ORDER NUMBER"   "ORDER DATE"     "CUSTOMER EMAIL" "PRODUCT  TITLE"
[5] "AMOUNT"        
$`ORDER NUMBER`
[1] "-ORDER NUMBER" "-ORDER NUMBER"

$`ORDER DATE`
[1] "-ORDER DATE" "-ORDER DATE" "-ORDER DATE" "-ORDER DATE"

$`CUSTOMER EMAIL`
[1] "CUSTOMER EMAIL"

$`PRODUCT  TITLE`
[1] "PRODUCT  TITLE"

$AMOUNT
[1] "-AMOUNT" "-AMOUNT" "-AMOUNT" "-AMOUNT" "-AMOUNT" "-AMOUNT" "-AMOUNT"
[8] "-AMOUNT"



Zadanie 10:

W wektorze pracownik_umiejetnosci poszukaj pracowników, którzy są zdefiniowani jako „Pro” lub „Medium”.

Wynikiem powinna być macierz, która zawiera imię i nazwisko pracownika w pierwszej kolumnie, a poziom umiejętności (bez nawiasów) w drugiej kolumnie.

Pracownicy, którzy nie są zakwalifikowani, powinni otrzymać brakujące wartości w obu kolumnach.

In [ ]:
# wyrażenie regularne do wyszukania poziomów "Pro" lub "Medium"
poziom_umiejetnosci <- "(Pro|Medium)"

# indeksy pracowników spełniających warunek
indeksy_pracownikow <- grep(poziom_umiejetnosci, pracownik_umiejetnosci)

# wyciągnięcie imion i nazwisk oraz poziomów umiejętności
pracownicy_wymagani <- pracownik_umiejetnosci[indeksy_pracownikow]
imiona_nazwiska <- gsub("\\s\\(.*", "", pracownicy_wymagani)
poziomy_umiejetnosci <- gsub(".*\\(|\\)", "", pracownicy_wymagani)

# utworzenie macierzy z danymi
macierz_pracownicy <- cbind(imiona_nazwiska, poziomy_umiejetnosci)

macierz_pracownicy

imiona_nazwiska poziomy_umiejetnosci
[1,] Marta Górska    Pro                 
[2,] Krzysztof Biały Pro                 
[3,] Sarah Machoń    Medium

Zadanie 11:

a) Stworz wektor x zawierajacy wszystkie znaki odpowiadajace wartosciom liczbowym z zakresu 1:128.

b) Wyswietl wszystkie znaki z wektora x, ktore odpowiadaja liczbom lub literom malym lub wielkim.

c) Wyswietl wszystkie znaki z wektora x, ktore odpowiadaja liczbom lub znakom oddzielajacym tekst tj. spacja, tabulator etc.

b) Wyswietl wszystkie znaki z wektora x, ktore nie odpowiadaja liczbom.

In [ ]:
# x <- chartoRaw(as.character(1:128))
x <- as.raw(1:128)
x

# raczje źle, bo wyświetla zupełnie coś innego
x[grep("[a-zA-Z0-9]", x)]
rawToChar(x[grep("[a-zA-Z0-9]", x)])
x[grep("[0-9\\s]", x)]
rawToChar(x[grep("[0-9\\s]", x)])
x[grep("[^0-9]", x)]
rawToChar(x[grep("[^0-9]", x)])

  [1] 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13 14 15 16 17 18 19
 [26] 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32
 [51] 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 40 41 42 43 44 45 46 47 48 49 4a 4b
 [76] 4c 4d 4e 4f 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 60 61 62 63 64
[101] 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d
[126] 7e 7f 80

  [1] 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13 14 15 16 17 18 19
 [26] 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32
 [51] 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 40 41 42 43 44 45 46 47 48 49 4a 4b
 [76] 4c 4d 4e 4f 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 60 61 62 63 64
[101] 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d
[126] 7e 7f 80

[1] "\001\002\003\004\005\006\a\b\t\n\v\f\r\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037 !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\177\x80"

  [1] 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13 14 15 16 17 18 19
 [26] 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32
 [51] 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 40 41 42 43 44 45 46 47 48 49 4a 4b
 [76] 4c 4d 4e 4f 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 60 61 62 63 64
[101] 65 66 67 68 69 6a 6b 6c 6d 6e 6f 70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d
[126] 7e 7f 80

[1] "\001\002\003\004\005\006\a\b\t\n\v\f\r\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037 !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\177\x80"

 [1] 0a 0b 0c 0d 0e 0f 1a 1b 1c 1d 1e 1f 2a 2b 2c 2d 2e 2f 3a 3b 3c 3d 3e 3f 4a
[26] 4b 4c 4d 4e 4f 5a 5b 5c 5d 5e 5f 6a 6b 6c 6d 6e 6f 7a 7b 7c 7d 7e 7f

[1] "\n\v\f\r\016\017\032\033\034\035\036\037*+,-./:;<=>?JKLMNOZ[\\]^_jklmnoz{|}~\177"

Zadanie 12:

a) Stworz wektor y zawierajacy nastepujace imiona: ("Jacek", "Kasia", "Małgosia","Elżbieta","joasia").

b) Stworz wyrazenie regularne, ktore spowoduje wybranie tylko imion: "Kasia","joasia".

c) Stworz wyrazenie regularne, ktore spowoduje wybranie tylko imion: "Jacek", "Kasia".

In [ ]:
y <- c("Jacek", "Kasia", "Małgosia","Elżbieta","joasia")
y

# Można chyba pominąć "^"
y[grep("^Kasia|^joasia", y)]
y[grep("^Jacek|^Kasia", y)]

[1] "Jacek"    "Kasia"    "Małgosia" "Elżbieta" "joasia"

[1] "Kasia"  "joasia"

[1] "Jacek" "Kasia"

Zadanie 13:

a) Stwotrz obiekt "dane" na podstawie nastepujacego wektora: c("1", "1 2", "12a3", "1223", "122234", "212234","1 22 3").

b) Stworz wyrazenie regularne znajdujace elementy wektora "dane", konczace sie na "2" lub "3".

c) Stworz wyrazenie regularne znajdujace elementy wektora "dane", posiadajace od jedej do trzech "2" nie bedacych jednoczesnie poczatkiem ani koncem tekstu.

d) Stworz wyrazenie regularne znajdujace elementy wektora "dane", posiadajace male litery lub spacje.

In [ ]:
dane <- c("1", "1 2", "12a3", "1223", "122234", "212234","1 22 3")

grep("[23]$", dane, value = T)

grep("^[^2]*2[^2]*2[^2]*2?[^2]*$", dane, value = T)

grep("[a-z ]", dane, value = T)

[1] "1 2"    "12a3"   "1223"   "1 22 3"

[1] "1223"   "122234" "212234" "1 22 3"

[1] "1 2"    "12a3"   "1 22 3"

Zadanie_14:

a) Stworz macierz rozmiaru "10X10" z wartosciami losowymi z rozkladu rownomiernego.

b) Stworz funkcje "Funkcja" ktora zwracac bedzie do obiektu "wynik_14" wartosc srednia dla kazdej kolumny macierzy wejsciowej.

c) Stworz "Funkcja_env" ktora bedzie "srodowiskowa" wersja powyzszej funkcji. Powinna ona nie zwracac zadnego obiektu, lecz umieszczac wynikowy obiekt w srodowisku, ktore bedzie obiektem wejsciowym dla funkcji.

In [ ]:
matrix <- matrix(runif(100), nrow = 10, ncol = 10)

Funkcja <- function(matrix) {
  wynik_14 <- apply(matrix, 2, mean)
  return(wynik_14)
}


Funkcja_env <- function(matrix) {
  assign("wynik_14", apply(matrix, 2, mean), envir = .GlobalEnv)
}

Funkcja(matrix)
wynik_14
Funkcja_env(matrix)
wynik_14
rm(wynik_14)

[1] 0.4712410 0.4417048 0.3932820 0.4233015 0.3999820 0.6498466 0.5664295
 [8] 0.4554415 0.3000439 0.3602589

[1] 0.5561470 0.2571791 0.5814242 0.5183341 0.3835261 0.3781216 0.5100589
 [8] 0.3131112 0.5076520 0.4688361

[1] 0.4712410 0.4417048 0.3932820 0.4233015 0.3999820 0.6498466 0.5664295
 [8] 0.4554415 0.3000439 0.3602589

Zadanie_2:

a) Stworz srodowisko "Pierwsze".

b) Umiesc w srodowisku "Pierwsze" obiekt "x" przyjmujacy wartosc 10.

c) Stworz srodowisko "Drugie" w srodowisku "Pierwsze". (Po wyswietleniu obiektow znajdujacych sie w srodowisku "Pierwsze", srodowisko "Drugie" powinno byc tam widoczne)

d) Umiesc w srodowisku "Drugie" obiekt "y" przyjmujacy wartosc 20.

e) Stworz funkcje zamieniajaca wartosc obiektu "x" w srodowisku "Pierwsze" na warotsc z obiektu "y" ze srodowiska "Drugie". Funkcja przyjmuje jako argument srodowisko.

In [ ]:
# Nie wiem czy to w ogóle działa

adresy_miasta_ulica <- gsub("(.) (.), (.*)", "\1,\2,\3", adresy)
adresy_miasta_ulica <- strsplit(adresy_miasta_ulica, ",")
adresy_miasta_ulica <- lapply(adresy_miasta_ulica, function(x) c(x[1], x[2], x[3]))
adresy_miasta_ulica <- do.call(rbind, adresy_miasta_ulica)

adresy_miasta_ulica


[,1]              [,2]           [,3]
[1,] Kasztanowa 14      Bielsko Biała NA  
[2,] Łąki Zielonej 152  Katowice      NA  
[3,] Specerow\001      \002           \003